//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string abrirToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("abrirToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string btnAdicionar_Text {
            get {
                return ResourceManager.GetString("btnAdicionar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeja.
        /// </summary>
        internal static string btnBandeja_Text {
            get {
                return ResourceManager.GetString("btnBandeja.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string btnCancelar_Text {
            get {
                return ResourceManager.GetString("btnCancelar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string btnEditar_Text {
            get {
                return ResourceManager.GetString("btnEditar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string btnExcluir_Text {
            get {
                return ResourceManager.GetString("btnExcluir.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        internal static string btnFiltrar_Text {
            get {
                return ResourceManager.GetString("btnFiltrar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir.
        /// </summary>
        internal static string btnInserir_Text {
            get {
                return ResourceManager.GetString("btnInserir.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin_Text {
            get {
                return ResourceManager.GetString("btnLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string btnSalvar_Text {
            get {
                return ResourceManager.GetString("btnSalvar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastros.
        /// </summary>
        internal static string cadastrosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cadastrosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string clientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string configuracoesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("configuracoesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_button {
            get {
                object obj = ResourceManager.GetObject("edit-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrar.
        /// </summary>
        internal static string encerarToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("encerarToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanhol.
        /// </summary>
        internal static string espanhol_Text {
            get {
                return ResourceManager.GetString("espanhol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string FeatureCliente {
            get {
                return ResourceManager.GetString("FeatureCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        internal static string FeatureFuncionario {
            get {
                return ResourceManager.GetString("FeatureFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrediente.
        /// </summary>
        internal static string FeatureIngrediente {
            get {
                return ResourceManager.GetString("FeatureIngrediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string FeatureLogin {
            get {
                return ResourceManager.GetString("FeatureLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        internal static string FeatureProduto {
            get {
                return ResourceManager.GetString("FeatureProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabor.
        /// </summary>
        internal static string FeatureSabor {
            get {
                return ResourceManager.GetString("FeatureSabor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string FeatureValor {
            get {
                return ResourceManager.GetString("FeatureValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        internal static string funcionariosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("funcionariosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui Habilitação?.
        /// </summary>
        internal static string grupoHabilitacao_Text {
            get {
                return ResourceManager.GetString("grupoHabilitacao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomais.
        /// </summary>
        internal static string idiomasToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("idiomasToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        internal static string ingles_Text {
            get {
                return ResourceManager.GetString("ingles.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredientes.
        /// </summary>
        internal static string ingredientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("ingredientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        internal static string lbBairro_Text {
            get {
                return ResourceManager.GetString("lbBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        internal static string lbCategorias_Text {
            get {
                return ResourceManager.GetString("lbCategorias.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        internal static string lbCep_Text {
            get {
                return ResourceManager.GetString("lbCep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string lbCidade_Text {
            get {
                return ResourceManager.GetString("lbCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha.
        /// </summary>
        internal static string lbComfirmarSenha_Text {
            get {
                return ResourceManager.GetString("lbComfirmarSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        internal static string lbComplemento_Text {
            get {
                return ResourceManager.GetString("lbComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string lbCpf_Text {
            get {
                return ResourceManager.GetString("lbCpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Vencimento.
        /// </summary>
        internal static string lbDataVencimento_Text {
            get {
                return ResourceManager.GetString("lbDataVencimento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lbEmail_Text {
            get {
                return ResourceManager.GetString("lbEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        internal static string lbEndereco_Text {
            get {
                return ResourceManager.GetString("lbEndereco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string lbFoto_Text {
            get {
                return ResourceManager.GetString("lbFoto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lbId_Text {
            get {
                return ResourceManager.GetString("lbId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredientes.
        /// </summary>
        internal static string lbIngredientes_Text {
            get {
                return ResourceManager.GetString("lbIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        internal static string lbMatricula_Text {
            get {
                return ResourceManager.GetString("lbMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ML.
        /// </summary>
        internal static string lbMl_Text {
            get {
                return ResourceManager.GetString("lbMl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string lbNome_Text {
            get {
                return ResourceManager.GetString("lbNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo.
        /// </summary>
        internal static string lbNomeCompleto_Text {
            get {
                return ResourceManager.GetString("lbNomeCompleto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string lbNumero_Text {
            get {
                return ResourceManager.GetString("lbNumero.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        internal static string lbObservacoes_Text {
            get {
                return ResourceManager.GetString("lbObservacoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string lbPais_Text {
            get {
                return ResourceManager.GetString("lbPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizzaria do Zé.
        /// </summary>
        internal static string lbPizzariaNome_Text {
            get {
                return ResourceManager.GetString("lbPizzariaNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua.
        /// </summary>
        internal static string lbRua_Text {
            get {
                return ResourceManager.GetString("lbRua.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string lbSenha_Text {
            get {
                return ResourceManager.GetString("lbSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        internal static string lbTamanho_Text {
            get {
                return ResourceManager.GetString("lbTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string lbTelefone_Text {
            get {
                return ResourceManager.GetString("lbTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string lbTipo_Text {
            get {
                return ResourceManager.GetString("lbTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        internal static string lbUf_Text {
            get {
                return ResourceManager.GetString("lbUf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string lbUsuario_Text {
            get {
                return ResourceManager.GetString("lbUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string lbValor_Text {
            get {
                return ResourceManager.GetString("lbValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Borda Especial.
        /// </summary>
        internal static string lbValorBordaEspecial_Text {
            get {
                return ResourceManager.GetString("lbValorBordaEspecial.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Borda Normal.
        /// </summary>
        internal static string lbValorBordaNormal_Text {
            get {
                return ResourceManager.GetString("lbValorBordaNormal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Pizza Especial.
        /// </summary>
        internal static string lbValorPizzaEspecial_Text {
            get {
                return ResourceManager.GetString("lbValorPizzaEspecial.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Pizza Tradicional.
        /// </summary>
        internal static string lbValorPizzaTradicional_Text {
            get {
                return ResourceManager.GetString("lbValorPizzaTradicional.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listando.
        /// </summary>
        internal static string Listando {
            get {
                return ResourceManager.GetString("Listando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        internal static string Listar {
            get {
                return ResourceManager.GetString("Listar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_ {
            get {
                object obj = ResourceManager.GetObject("login-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir o dado?.
        /// </summary>
        internal static string MensagemConfirmacaoExclusao {
            get {
                return ResourceManager.GetString("MensagemConfirmacaoExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente cancelar? .
        /// </summary>
        internal static string MensagemDesejaCancelar {
            get {
                return ResourceManager.GetString("MensagemDesejaCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente salvar as informações?.
        /// </summary>
        internal static string MensagemDesejaSalvar {
            get {
                return ResourceManager.GetString("MensagemDesejaSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item editado com sucesso!.
        /// </summary>
        internal static string MensagemEditadoSucesso {
            get {
                return ResourceManager.GetString("MensagemEditadoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item excluído com sucesso!.
        /// </summary>
        internal static string MensagemExcluidoSucesso {
            get {
                return ResourceManager.GetString("MensagemExcluidoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma foi atualizado para potuguês.
        /// </summary>
        internal static string MensagemIdiomaAtualizado {
            get {
                return ResourceManager.GetString("MensagemIdiomaAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item salvo com sucesso!.
        /// </summary>
        internal static string MensagemInseridoSucesso {
            get {
                return ResourceManager.GetString("MensagemInseridoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum item editado.
        /// </summary>
        internal static string MensagemNenhumItemEditado {
            get {
                return ResourceManager.GetString("MensagemNenhumItemEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum item excluído.
        /// </summary>
        internal static string MensagemNenhumItemExcluido {
            get {
                return ResourceManager.GetString("MensagemNenhumItemExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum item inserido.
        /// </summary>
        internal static string MensagemNenhumItemInserido {
            get {
                return ResourceManager.GetString("MensagemNenhumItemInserido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente sair?.
        /// </summary>
        internal static string mensagemSairSistema {
            get {
                return ResourceManager.GetString("mensagemSairSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string nao_Text {
            get {
                return ResourceManager.GetString("nao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string Novo {
            get {
                return ResourceManager.GetString("Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        internal static string pedidosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pedidosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string portugues_Text {
            get {
                return ResourceManager.GetString("portugues.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string produtosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("produtosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios.
        /// </summary>
        internal static string relatoriosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("relatoriosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabores.
        /// </summary>
        internal static string saboresToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saboresToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string sairToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("sairToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Idioma.
        /// </summary>
        internal static string selecionarIdioma_Text {
            get {
                return ResourceManager.GetString("selecionarIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string sim_Text {
            get {
                return ResourceManager.GetString("sim.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string sobreToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("sobreToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string TelaCadastroClienteForm_Text {
            get {
                return ResourceManager.GetString("TelaCadastroClienteForm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        internal static string TelaCadastroFuncionarioForm_Text {
            get {
                return ResourceManager.GetString("TelaCadastroFuncionarioForm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrediente.
        /// </summary>
        internal static string TelaCadastroIngredienteForm_Text {
            get {
                return ResourceManager.GetString("TelaCadastroIngredienteForm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string TelaCadastroLoginForm_Text {
            get {
                return ResourceManager.GetString("TelaCadastroLoginForm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        internal static string TelaCadastroProdutoForm_Text {
            get {
                return ResourceManager.GetString("TelaCadastroProdutoForm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabor.
        /// </summary>
        internal static string TelaCadastroSaborForm_Text {
            get {
                return ResourceManager.GetString("TelaCadastroSaborForm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizzaria do Zé.
        /// </summary>
        internal static string TelaPrincipalForm_Text {
            get {
                return ResourceManager.GetString("TelaPrincipalForm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        internal static string valoresToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("valoresToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
